name: Deploy Code

on:
  push:
    branches:
      - main

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # or the version of PHP you need

    - name: Sync files
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: 139.59.5.82
        username: root
        password: A\7w9WF.]5XWP/mCare
        script: |
          rsync -avz --delete --exclude '.git' $GITHUB_WORKSPACE/ /var/www/html/test/
